In [2]:
#Day 31
#Numpy 

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
#import etmek isim atanır genelde np
import numpy as np

In [ ]:
#numpy array


In [9]:
my_list = [1,2,3,4,5]
type(my_list)  #list


list

In [12]:
arr=np.array(my_list)
type(arr)  #numpy.ndarray
#numpy kendi dizisidir list sayılmaz artık

numpy.ndarray

In [13]:
print(arr)

[1 2 3 4 5]


In [ ]:
#acaba list özelliklerini taşıyor mu?
arr[0]#indeksleme yapabiliriz

1

In [15]:
arr[0]=90#elemanlaru da değiştirebiliriz

In [16]:
print(arr[0])

90


In [ ]:
#arr. dersek farklılıklar burda başlar numpy arraylerin birçok methodu vardır listten farklı olarak
#zaten listelere benzer ama kendi içinde hesaplama ve matrisler için optimize edilmiştir

#normalde liste ile de bu matris görüntüsü yapılabilir
matrix_list = [[1,2,3],[4,5,6],[7,8,9]]#liste içinde liste
type(matrix_list)  #list

list

In [ ]:
nump_listem=np.array(matrix_list)  #list yapısını arraye çevirdik np ile aynı liste gibidir  sadece tam matrix gibi gözükür 

In [20]:
type(nump_listem)

numpy.ndarray

In [21]:
print(nump_listem)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
nump_listem.shape  #matrisin şekli (3,3) 3 satır 3 sütun bunu verir

(3, 3)

In [ ]:
#array oluşturma***
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
type(arr2) 

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [24]:
#arange nedir?
arr3=np.arange(0,11)  #0 dan 10 a kadar sayılar oluşturur 11 dahil değil
print(arr3)
type(arr3)
#belli aralıklarla da oluşturabiliriz
arr4=np.arange(0,21,2)  #0 dan 20 ye kadar
print(arr4)
#2 şer 2 şer artar
type(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]


numpy.ndarray

In [26]:
#linspace nedir? belli bir aralıkta eşit aralıklı sayılar oluşturur
arr5=np.linspace(0,10,5)  #0 ile 10 arasında 5 sayı oluşturur
print(arr5)
type(arr5)

arr6=np.linspace(0,10,20)  #0 ile 10 arasında 20 sayı oluşturur
print(arr6)
type(arr6)


[ 0.   2.5  5.   7.5 10. ]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


numpy.ndarray

In [27]:
#numpy array metodları


In [28]:
my_numpy_list=np.array(range(0,20))

In [29]:
print(my_numpy_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
my_numpy_list[4:9]#slicing de çalışır list gibi

array([4, 5, 6, 7, 8])

In [31]:
 my_numpy_list[2:4]=-10 #bunu normalde listte yapamazsın ama numpyda al şu aralığı şuna eşitle deiyebilirsin

In [34]:
print(my_numpy_list)

[  0   1 -10 -10   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [35]:
#mesela elemanları rastgele değerlerden oluşan np dizisi yapalım 
#normalde nasıldı değişkenadı = np.array([dizi])
#veya np.array(range(x,y))

rastgele_de=np.random.randint(0,100,10)  #0 ile 100 arasında 10 tane rastgele tam sayı oluşturur
print(rastgele_de)

[40 57 25 13 55 18 35 64 44 60]


In [36]:
#bu listede büyük 50 olanları görelim mesela normal listlerde yapamayız ama numpyda mümkün
rastgele_de>50

array([False,  True, False, False,  True, False, False,  True, False,
        True])